# Generated by Django 4.2.3 on 2024-08-07 18:33

import CMS.sharedutils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_priceapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameapproval',
            name='issuance_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='boxapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='cadcapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='comparativeapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='compositionapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='insertapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='layoutapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='nameapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='priceapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='registerationlicense',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
        migrations.AlterField(
            model_name='stabilityapproval',
            name='attachment',
            field=models.FileField(upload_to=CMS.sharedutils.upload_to),
        ),
    ]
