# Generated by Django 5.0.7 on 2024-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_nameapproval_issuance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceapproval',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
