# Generated by Django 4.2.3 on 2024-08-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_priceapproval_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='compositionapproval',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (0, 'Superseded')], default=1, max_length=1),
        ),
    ]
