# Generated by Django 4.2.3 on 2024-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_compositionapproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationlicense',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stabilityapproval',
            name='study_length',
            field=models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (18, '18 Months'), (24, '24 Months'), (36, '36 Months')], default=3),
        ),
    ]
